In [1]:
import pandas as pd
import numpy as np
import csv
import seaborn as sb
import json
%matplotlib inline

In [157]:
df_credits = pd.read_csv('tmdb_5000_credits.csv')
df_movies = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
df_credits.sample(10)

,movie_id,title,cast,crew
3978,351043,Amnesiac,"[{""cast_id"": 1, ""character"": ""Woman"", ""credit_...","[{""credit_id"": ""55b040b69251411e0b00d184"", ""de..."
1239,11370,The Musketeer,"[{""cast_id"": 1, ""character"": ""The Queen"", ""cre...","[{""credit_id"": ""56ca389d925141172f008c55"", ""de..."
3932,17734,Thirteen Conversations About One Thing,"[{""cast_id"": 1, ""character"": ""Walker"", ""credit...","[{""credit_id"": ""52fe47439251416c7509335f"", ""de..."
3660,12486,Farce of the Penguins,"[{""cast_id"": 2, ""character"": ""Narrator (voice)...","[{""credit_id"": ""52fe44ea9251416c750456fb"", ""de..."
1905,43931,My Soul to Take,"[{""cast_id"": 3, ""character"": ""Adam \""Bug\"" Hel...","[{""credit_id"": ""53578493c3a36855f2002905"", ""de..."
3405,13001,Stargate: The Ark of Truth,"[{""cast_id"": 9, ""character"": ""Cameron Mitchell...","[{""credit_id"": ""52fe452d9251416c7504e3ed"", ""de..."
4033,45132,Super,"[{""cast_id"": 3, ""character"": ""Frank Darbo"", ""c...","[{""credit_id"": ""5677fc029251417845001b2d"", ""de..."
3836,40505,I Got the Hook Up,"[{""cast_id"": 1002, ""character"": ""Black"", ""cred...","[{""credit_id"": ""52fe4595c3a36847f80cf533"", ""de..."
254,41513,The Smurfs,"[{""cast_id"": 7, ""character"": ""Gargamel"", ""cred...","[{""credit_id"": ""52fe45cfc3a36847f80dbb31"", ""de..."
114,674,Harry Potter and the Goblet of Fire,"[{""cast_id"": 1, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4268c3a36847f801c275"", ""de..."

In [4]:
df_credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 93.9+ KB

In [5]:
df_movies.head(10)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004

In [6]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 506.6+ KB

In [7]:
df_movies.runtime.isnull().sum()

2

In [8]:
df_movies.loc[df_movies.runtime.isnull()]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
2656,15000000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,370980,"[{""id"": 717, ""name"": ""pope""}, {""id"": 5565, ""na...",it,Chiamatemi Francesco - Il Papa della gente,NaN,0.738646,"[{""name"": ""Taodue Film"", ""id"": 45724}]","[{""iso_3166_1"": ""IT"", ""name"": ""Italy""}]",2015-12-03,0,NaN,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,NaN,Chiamatemi Francesco - Il Papa della gente,7.3,12
4140,2,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,459488,"[{""id"": 6027, ""name"": ""music""}, {""id"": 225822,...",en,"To Be Frank, Sinatra at 100",NaN,0.050625,"[{""name"": ""Eyeline Entertainment"", ""id"": 60343}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",2015-12-12,0,NaN,[],Released,NaN,"To Be Frank, Sinatra at 100",0.0,0

In [9]:
df_movies.iloc[3310]

budget                                                            7700000
genres                  [{"id": 18, "name": "Drama"}, {"id": 10752, "n...
homepage                                                              NaN
id                                                                 283708
keywords                [{"id": 657, "name": "fire"}, {"id": 1517, "na...
original_language                                                      fr
original_title                                            Loin des hommes
overview                A French teacher in a small Algerian village d...
popularity                                                        3.36397
production_companies    [{"name": "Procirep", "id": 311}, {"name": "Ca...
production_countries             [{"iso_3166_1": "FR", "name": "France"}]
release_date                                                   2014-08-30
revenue                                                                 0
runtime                                                               110
spoken_languages        [{"iso_639_1": "ar", "name": "\u0627\u0644\u06...
status                                                           Released
tagline                                                               NaN
title                                                        Far from Men
vote_average                                                          6.6
vote_count                                                             43
Name: 3310, dtype: object

In [10]:
df_movies.status.value_counts()

Released           4795
Rumored               5
Post Production       3
Name: status, dtype: int64

In [11]:
df_movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

### Assessing 
#### Quality
    - id datatype is int64 instead of string
    - release_date to datetime type.
    - extracting the exact genre from the text in genre column
    - extracting the exact companies from the text in production_companies column
    - extracting the exact countries from the text in production_countries column
    - extracting languages from the test in spoken_languages column.
    - missing values from the release_date (4553)
    - missing values from the runtime (2656,4140)
    - droping unnecessary columns.[homepage,keywords,original_title,overview,tagline]
    
#### Tidiness

## Cleaning

In [158]:
#extracting the exact genre from the text in genre column
df_movies['genre_n'] = ""

In [159]:
list_of_genres = []
seperator = ', '
for ind in df_movies.index:
    genres_list_json_parsed = json.loads(df_movies['genres'][ind])
    updated_genres_list = list(map(lambda d: d['name'], genres_list_json_parsed))
    stringified_list = seperator.join(updated_genres_list)
    list_of_genres.append(stringified_list)

In [160]:
df_movies['genre_n'] = list_of_genres

In [161]:
df_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,genre_n
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction"
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Adventure, Fantasy, Action"
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"Action, Adventure, Crime"
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"Action, Crime, Drama, Thriller"
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"Action, Adventure, Science Fiction"

In [108]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   budget                  4803 non-null   int64
 1   id                      4803 non-null   object
 2   original_language       4803 non-null   object
 3   popularity              4803 non-null   float64
 4   release_date            4802 non-null   datetime64[ns]
 5   revenue                 4803 non-null   int64
 6   runtime                 4801 non-null   float64
 7   status                  4803 non-null   object
 8   title                   4803 non-null   object
 9   vote_average            4803 non-null   float64
 10  vote_count              4803 non-null   int64
 11  genre_n                 4803 non-null   object
 12  production_companies_n  4803 non-null   object
 13  production_countries_n  4803 non-null   object
 14  spoken_languages_n      4803 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(3), object(8)
memory usage: 412.8+ KB

In [162]:
# Changing release_date to datetime.
df_movies['release_date'] = pd.to_datetime(df_movies['release_date'])

In [183]:
## Dropping homepage column.keywords,original_title,overview,tagline
df_movies.drop(['homepage','keywords','original_title','overview','tagline'], axis=1,inplace=True)
#df_movies.drop(['genres'],axis=1,inplace = True)

In [163]:
#id datatype is int64 instead of string
df_movies['id']=df_movies['id'].astype(str)

In [164]:
df_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,genre_n
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction"
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Adventure, Fantasy, Action"
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"Action, Adventure, Crime"
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"Action, Crime, Drama, Thriller"
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"Action, Adventure, Science Fiction"

In [165]:
# extracting the exact companies from the text in production_companies column
list_of_companies = []
seperator = ', '
for ind in df_movies.index:
    companies_list_json_parsed = json.loads(df_movies['production_companies'][ind])
    updated_companies_list = list(map(lambda d: d['name'], companies_list_json_parsed))
    stringified_list = seperator.join(updated_companies_list)
    list_of_companies.append(stringified_list)

In [166]:
df_movies['production_companies_n']=""

In [167]:
df_movies['production_companies_n'] = list_of_companies

In [189]:
df_movies.drop(['production_companies'],axis=1,inplace = True)

In [168]:
#extracting the exact countries from the text in production_countries column
list_of_countries = []
seperator = ', '
for ind in df_movies.index:
    countries_list_json_parsed = json.loads(df_movies['production_countries'][ind])
    updated_countries_list = list(map(lambda d: d['name'], countries_list_json_parsed))
    stringified_list = seperator.join(updated_countries_list)
    list_of_countries.append(stringified_list)

In [169]:
df_movies['production_countries_n']=""

In [170]:
df_movies['production_countries_n'] = list_of_countries

In [188]:
df_movies.drop(['production_countries'],axis=1,inplace = True)

In [171]:
#extracting languages from the test in spoken_languages column.
list_of_languages = []
seperator = ', '
for ind in df_movies.index:
    languages_list_json_parsed = json.loads(df_movies['spoken_languages'][ind])
    updated_languages_list = list(map(lambda d: d['name'], languages_list_json_parsed))
    stringified_list = seperator.join(updated_languages_list)
    list_of_languages.append(stringified_list)

In [172]:
df_movies['spoken_languages_n']=""

In [173]:
df_movies['spoken_languages_n']= list_of_languages

In [187]:
df_movies.drop(['spoken_languages'],axis=1,inplace = True)

In [184]:
df_movies.sample(20)

,budget,genres,id,original_language,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,title,vote_average,vote_count,genre_n,production_companies_n,production_countries_n,spoken_languages_n
3789,9500000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",44945,en,21.230737,"[{""name"": ""Nu Image Films"", ""id"": 925}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-09-10,120000,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Trust,6.6,307,"Crime, Drama, Thriller","Nu Image Films, Millennium Films, Dark Harbor ...",United States of America,English
830,30000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",393,en,50.622607,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-04-16,152159461,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Kill Bill: Vol. 2,7.6,3948,"Action, Crime, Thriller","Miramax Films, A Band Apart, Super Cool ManChu",United States of America,"English, 普通话, Español, 广州话 / 廣州話"
645,50000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",9208,en,22.769108,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1996-02-09,150270147,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Broken Arrow,5.7,453,"Action, Adventure, Drama, Thriller","Twentieth Century Fox Film Corporation, WCG En...",United States of America,English
4465,780000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",10105,en,6.003418,"[{""name"": ""Excel Entertainment"", ""id"": 2934}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2003-09-11,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Saints and Soldiers,6.6,98,"Action, Adventure, Drama, History, War",Excel Entertainment,United States of America,"English, Deutsch"
3357,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 27, ""name...",1696,en,16.754452,"[{""name"": ""Lions Gate Films"", ""id"": 35}, {""nam...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2005-07-22,0,107.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...",Released,The Devil's Rejects,6.6,322,"Drama, Horror, Crime","Lions Gate Films, Cinerenta Medienbeteiligungs...","Germany, United States of America","Español, English"
1207,40000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",10761,en,19.574774,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2008-05-02,84601681,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Made of Honor,6.0,394,"Comedy, Romance","Columbia Pictures, Original Film","United Kingdom, United States of America","English, Français, Pусский"
2388,18000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",332411,en,10.144222,"[{""name"": ""Patriot Pictures"", ""id"": 2373}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-04-14,0,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,I Am Wrath,4.5,179,"Action, Crime, Drama, Thriller","Patriot Pictures, Vallelonga Productions, Veng...",United States of America,English
1166,40000000,"[{""id"": 35, ""name"": ""Comedy""}]",257091,en,36.301202,"[{""name"": ""Gary Sanchez Productions"", ""id"": 47...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-03-26,111811453,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Get Hard,5.9,944,Comedy,"Gary Sanchez Productions, Warner Bros.",United States of America,English
4528,500000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",12281,en,8.519202,"[{""name"": ""Whitewater Films"", ""id"": 3095}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-01-15,603943,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Mean Creek,6.9,106,"Crime, Drama",Whitewater Films,United States of America,English
2761,0,"[{""id"": 35, ""name"": ""Comedy""}]",14577,en,9.066881,"[{""name"": ""Robert Simonds Productions"", ""id"": ...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",1998-06-12,0,82.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dirty Work,6.5,66,Comedy,"Robert Simonds Productions, Metro-Goldwyn-Maye...","Canada, United States of America",English
2376,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",10739,en,8.945081,"[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2003-08-27,0,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Anything Else,6.2,149,"Comedy, Romance","DreamWorks SKG, Granada Film Productions, Perd...","United Kingdom, Netherlands, France",English
1733,28000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",23172,en,14.639324,"[{""name"": ""Robert Simonds Productions"", ""id"": ...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-01-15,45236543,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Spy Next Door,5.5,345,"Action, Comedy, Family","Robert Simonds Productions, Relativity Media, ...",United States of America,English
3887,4000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",627,en,63.513324,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",1996-02-23,16491080,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Trainspotting,7.8,2655,"Drama, Crime","Miramax Films, Channel Four Films, Noel Gay Mo...",United Kingdom,English
3769,4000000,"[{""id"": 18, ""name"": ""Drama""}]",10132,en,4.541908,"[{""name"": ""Cineplex-Odeon Films"", ""id"": 5231},...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",1988-12-21,3468572,110.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Talk Radio,6.7,46,Drama,"Cineplex-Odeon Films, Ten-Four Productions","Canada, United States of America",English
1796,26000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name...",7445,en,22.076380,"[{""name"": ""Lionsgate"", ""id"": 1632}, {""name"": ""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-01-27,43318349,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Brothers,6.8,633,"Drama, Thriller, War","Lionsgate, Relativity Media, Sighvatsson Films...",United States of America,"English, Français"
3518,6000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",8982,th,11.818320,"[{""name"": ""The Weinstein Company"", ""id"": 308},...","[{""iso_3166_1"": ""TH"", ""name"": ""Thailand""}, {""i...",2005-08-11,27165581,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The Protector,6.8,167,"Action, Crime, Drama, Thriller","The Weinstein Company, Sahamongkol Film Intern...","Thailand, Australia","English, 普通话, ภาษาไทย, Tiếng Việt"
2532,18000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",9587,en,16.418639,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1994-12-21,0,115.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Little Women,7.0,215,"Drama, Romance",Columbia Pictures,United States of America,"English, Deutsch, Français"
2756,13000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",10691,en,6.130096,"[{""name"": ""Touchstone Pictures"", ""id"": 9195}, ...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2001-06-29,16929123,99.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...",Released,Crazy/Beautiful,6.6,96,"Drama, Romance","Touchstone Pictures, Ufland",United States of America,"Español, English"
3225,8000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",62676,en,0.034259,[],[],1999-06-04,1997807,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Limbo,7.0,17,"Adventure, Drama, Thriller",,,English
4724,10000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 14, ""name...",985,en,20.399578,"[{""name"": ""American Film Institute (AFI)"", ""id...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1977-03-19,7000000,89.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Eraserhead,7.5,485,"Drama, Fantasy, Horror, Science Fiction","American Film Institute (AFI), Libra Films",United States of America,English

## Analysis

## Which genres are most popular from year to year?

## What kinds of properties are associated withmovies that have high revenues?

In [190]:
df_movies.sort_values(by='revenue',ascending= False,na_position ='first').head(10)

,budget,genres,id,original_language,popularity,release_date,revenue,runtime,status,title,vote_average,vote_count,genre_n,production_companies_n,production_countries_n,spoken_languages_n
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,en,150.437577,2009-12-10,2787965087,162.0,Released,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction","Ingenious Film Partners, Twentieth Century Fox...","United States of America, United Kingdom","English, Español"
25,200000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",597,en,100.025899,1997-11-18,1845034188,194.0,Released,Titanic,7.5,7562,"Drama, Romance, Thriller","Paramount Pictures, Twentieth Century Fox Film...",United States of America,"English, Français, Deutsch, svenska, Italiano,..."
16,220000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",24428,en,144.448633,2012-04-25,1519557910,143.0,Released,The Avengers,7.4,11776,"Science Fiction, Action, Adventure","Paramount Pictures, Marvel Studios",United States of America,English
28,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",135397,en,418.708552,2015-06-09,1513528810,124.0,Released,Jurassic World,6.5,8662,"Action, Adventure, Science Fiction, Thriller","Universal Studios, Amblin Entertainment, Legen...",United States of America,English
44,190000000,"[{""id"": 28, ""name"": ""Action""}]",168259,en,102.322217,2015-04-01,1506249360,137.0,Released,Furious 7,7.3,4176,Action,"Universal Pictures, Original Film, Fuji Televi...","Japan, United States of America",English
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",99861,en,134.279229,2015-04-22,1405403694,141.0,Released,Avengers: Age of Ultron,7.3,6767,"Action, Adventure, Science Fiction","Marvel Studios, Prime Focus, Revolution Sun St...",United States of America,English
124,150000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 12, ""...",109445,en,165.125366,2013-11-27,1274219009,102.0,Released,Frozen,7.3,5295,"Animation, Adventure, Family","Walt Disney Pictures, Walt Disney Animation St...",United States of America,English
31,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",68721,en,77.682080,2013-04-18,1215439994,130.0,Released,Iron Man 3,6.8,8806,"Action, Adventure, Science Fiction",Marvel Studios,"China, United States of America",English
546,74000000,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 16, ""...",211672,en,875.581305,2015-06-17,1156730962,91.0,Released,Minions,6.4,4571,"Family, Animation, Adventure, Comedy","Universal Pictures, Illumination Entertainment",United States of America,English
26,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",271110,en,198.372395,2016-04-27,1153304495,147.0,Released,Captain America: Civil War,7.1,7241,"Adventure, Action, Science Fiction","Studio Babelsberg, Marvel Studios, Walt Disney...",United States of America,"Română, English, Deutsch, Pусский"